apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-dev

resources:
  - ../../base

replicas:
  - name: nginx
    count: 1

images:
  - name: nginx
    newName: 172.31.25.149:30002/devops-lab/jenkins-demo-app
    newTag: "4"

labels:
  - pairs:
      environment: dev
