apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-prod

resources:
  - ../../base

replicas:
  - name: nginx
    count: 4

images:
  - name: nginx
    newTag: "this-tag-does-not-exist-lab"

labels:
  - pairs:
      environment: prod
