apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: petclinic
    count: 1

images:
  - name: 172.31.25.149:30002/devops-lab/petclinic
    newTag: "test"

labels:
  - pairs:
      environment: dev
